server:
  port: 8081
  servlet:
    context-path: /auth

logging:
  level:
    root: DEBUG

########################################################################################
# Thymeleaf settings
########################################################################################

spring:
  thymeleaf:
    cache: false
    check-template: true
    check-template-location: true
    servlet:
      content-type: text/html
    enabled:  true
    encoding: UTF-8
    prefix: classpath:/templates/
    suffix: .html


  h2:
    console:
      enabled: true
